server:
     port: ${PORT:5000}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.piszeozfulrkhhhdlwrh.supabase.co:5432/postgres?createDatabaseIfnotExist=true&useTimezone=true&serverTimezone=UTC
    username: postgres
    password: J52Uew4qzR3Yydiy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    baseline-on-migrate: true