server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlserver.c4fxinpuyiw7.sa-east-1.rds.amazonaws.com:3306/frango_leleko?createDatabaseIfnotExist=true&useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin1021
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  flyway:
    baseline-on-migrate: true

    